### ISSUE TITLE
57a win_cursor_plus crash loop

### ISSUE THREAD

**Issue by Lokki-P** [Ractiv/touch_plus_source_code#14]
Win7 x64 Ultimate, Macbook Pro mid 2014.
As per title, same problem reported by Andrew on another site:

Build from most recent code now stucks in crashes loop for me http://screenshots.ryotsuke.ru/scr_b9869876fadd.png

**Comment by Ryotsuke** [comment]
Can confirm it still happens http://screenshots.ryotsuke.ru/scr_752f37885730.png with https://github.com/Ractiv/touch_plus_source_code/commit/ffeacca77c8383e0dfbe27a4217902c0053bdaf9 commit

**Comment by Ryotsuke** [comment]
This is no longer reproducible and needs to be closed
