### ISSUE TITLE
missing opencv

### ISSUE THREAD

**Issue by Lokki-P** [Ractiv/touch_plus_source_code#6]
Looks like you've lost opencv from dependencies in the shift to \windows\dependencies?

**Comment by Lokki-P** [comment]
Also SFML/lib directory, Etron libs, and turboJPG lib?

**Comment by sheley1998** [comment]
Good catch, accidentally excluded compiled libraries with gitignore. Should
be fixed now.

**Comment by Lokki-P** [comment]
All good now, thanks
